"""add external_key for idempotent statement import

Revision ID: 19d138a1d447
Revises: 7239cae9359c
Create Date: 2026-07-09 16:53:57.605823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d138a1d447'
down_revision = '7239cae9359c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_daily_expense_external_key', ['household_id', 'external_key'])

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_income_external_key', ['household_id', 'external_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_income_external_key', type_='unique')
        batch_op.drop_column('external_key')

    with op.batch_alter_table('daily_expenses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_daily_expense_external_key', type_='unique')
        batch_op.drop_column('external_key')

    # ### end Alembic commands ###
