"""parcelas em future_purchase

Revision ID: 4de078d8b8a9
Revises: c59e9702953d
Create Date: 2026-07-09 23:45:10.856283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de078d8b8a9'
down_revision = 'c59e9702953d'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='1' é obrigatório: sem ele, um ADD COLUMN NOT NULL falha
    # em qualquer tabela que já tenha linhas. As compras existentes viram à vista.
    with op.batch_alter_table('future_purchases', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('installments', sa.Integer(), nullable=False, server_default='1')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_purchases', schema=None) as batch_op:
        batch_op.drop_column('installments')

    # ### end Alembic commands ###
