"""liga parcela a compra futura

Revision ID: 60546d973b99
Revises: 4de078d8b8a9
Create Date: 2026-07-09 23:47:38.578146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60546d973b99'
down_revision = '4de078d8b8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'future_purchases', ['purchase_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_id')

    # ### end Alembic commands ###
