"""vigencia em fixed_expense, source e parcela em daily_expense, tabela installments

Revision ID: c59e9702953d
Revises: 19d138a1d447
Create Date: 2026-07-09 23:19:00.919510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59e9702953d'
down_revision = '19d138a1d447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_installments', sa.Integer(), nullable=False),
    sa.Column('current_installment', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installments_household_id'), ['household_id'], unique=False)

    with op.batch_alter_table('daily_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('installment_info', sa.String(length=10), nullable=True))

    with op.batch_alter_table('fixed_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_expenses', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('daily_expenses', schema=None) as batch_op:
        batch_op.drop_column('installment_info')
        batch_op.drop_column('source')

    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installments_household_id'))

    op.drop_table('installments')
    # ### end Alembic commands ###
